export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT"


export const CREATE_COMPANY = "CREATE_COMPANY"
export const CREATE_EMPLOYEE = "CREATE_EMPLOYEE"

export const FETCH_EMPLOYEES = "FETCH_EMPLOYEES"
export const FETCH_EMPLOYEE = "FETCH_EMPLOYEE"
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE"
export const EDIT_EMPLOYEE = "EDIT_EMPLOYEE"

export const FETCH_COMPANYS = "FETCH_COMPANYS"
export const FETCH_COMPANY = "FETCH_COMPANY"
export const DELETE_COMPANY = "DELETE_COMPANY"
export const EDIT_COMPANY = "EDIT_COMPANY"


export const ADD_WORK = "ADD_WORK"
export const DELETE_WORK = "DELETE_WORK"
export const ADD_COMPANY_WORKS = "ADD_COMPANY_WORKS"
export const ADD_EMPLOYEE_WORKS = "ADD_EMPLOYEE_WORKS"
export const GET_EMPLOYEE_WORKS = "GET_EMPLOYEE_WORKS"
export const GET_COMPANY_WORKS = "GET_COMPANY_WORKS"

export const IN_MANAGER = "IN_MANAGER"
export const OUT_MANAGER = "OUT_MANAGER"
export const FETCH_COMPANY_WORKS = "FETCH_COMPANY_WORKS"
export const FETCH_EMPLOYEE_WORKS = "FETCH_EMPLOYEE_WORKS"

export const SUCCESS = "SUCCESS"
export const ERROR = "ERROR"
export const CLOSE_MODAL = "CLOSE_MODAL"